export type ToolHub = "bizcard" | "qr" | "shortener" | "googlesabt";
export type ToolPageType = "industry" | "intent" | "guide" | "comparison";
export type PageStatus = "published" | "draft";

export type ToolRegistryEntry = {
  hub: ToolHub;
  slug: string;
  pageType: ToolPageType;
  status: PageStatus;
  primaryKeyword: string;
  secondaryKeywords: readonly string[];
  /** Short Persian label for hubs/grids */
  label: string;
  relatedSlugs: readonly string[];
  crossToolLinks?: readonly { hub: ToolHub; slug: string; anchor: string }[];
  /** Optional industry path for website/seo cross-links */
  industryPath?: string;
};

const BIZCARD_PAGES: ToolRegistryEntry[] = [
  {
    hub: "bizcard",
    slug: "restaurant",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال رستوران",
    secondaryKeywords: ["لینک منوی رستوران", "QR کارت رستوران", "کارت ویزیت کافه رستوران"],
    label: "رستوران",
    relatedSlugs: ["cafe", "salon", "online-shop", "instagram-business"],
    crossToolLinks: [
      { hub: "qr", slug: "menu", anchor: "ساخت QR منوی رستوران" },
      { hub: "shortener", slug: "instagram", anchor: "لینک کوتاه برای بیو اینستا" },
      { hub: "googlesabt", slug: "restaurant", anchor: "ثبت رستوران در گوگل مپ" },
    ],
    industryPath: "restaurant",
  },
  {
    hub: "bizcard",
    slug: "cafe",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال کافه",
    secondaryKeywords: ["لینک کافه", "QR منوی کافه", "کارت ویزیت کافی‌شاپ"],
    label: "کافه",
    relatedSlugs: ["restaurant", "salon", "instagram-business", "gym"],
    crossToolLinks: [
      { hub: "qr", slug: "wifi", anchor: "QR وای‌فای کافه" },
      { hub: "googlesabt", slug: "cafe", anchor: "ثبت کافه در گوگل مپ" },
    ],
    industryPath: "cafe",
  },
  {
    hub: "bizcard",
    slug: "doctor",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال پزشک",
    secondaryKeywords: ["کارت ویزیت مطب", "لینک نوبت پزشک", "کارت دیجیتال پزشک"],
    label: "پزشک",
    relatedSlugs: ["clinic", "dentist", "beauty-clinic", "consultant"],
    crossToolLinks: [
      { hub: "qr", slug: "vcard", anchor: "QR کارت ویزیت پزشک" },
      { hub: "googlesabt", slug: "doctor", anchor: "ثبت مطب در گوگل مپ" },
    ],
    industryPath: "doctor",
  },
  {
    hub: "bizcard",
    slug: "clinic",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال کلینیک",
    secondaryKeywords: ["لینک کلینیک", "کارت ویزیت مرکز درمانی"],
    label: "کلینیک",
    relatedSlugs: ["doctor", "dentist", "beauty-clinic", "consultant"],
    crossToolLinks: [{ hub: "googlesabt", slug: "clinic", anchor: "ثبت کلینیک در گوگل مپ" }],
    industryPath: "clinic",
  },
  {
    hub: "bizcard",
    slug: "dentist",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال دندانپزشک",
    secondaryKeywords: ["کارت ویزیت دندانپزشکی", "لینک مطب دندانپزشک"],
    label: "دندانپزشک",
    relatedSlugs: ["doctor", "clinic", "beauty-clinic"],
    crossToolLinks: [{ hub: "googlesabt", slug: "dentist", anchor: "ثبت دندانپزشکی در گوگل مپ" }],
    industryPath: "dentist",
  },
  {
    hub: "bizcard",
    slug: "beauty-clinic",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال کلینیک زیبایی",
    secondaryKeywords: ["کارت ویزیت پوست و مو", "لینک کلینیک زیبایی"],
    label: "کلینیک زیبایی",
    relatedSlugs: ["salon", "clinic", "doctor", "instagram-business"],
    crossToolLinks: [
      { hub: "googlesabt", slug: "beauty-clinic", anchor: "ثبت کلینیک زیبایی در گوگل مپ" },
    ],
    industryPath: "beauty-clinic",
  },
  {
    hub: "bizcard",
    slug: "lawyer",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال وکیل",
    secondaryKeywords: ["کارت ویزیت وکالت", "لینک دفتر وکیل"],
    label: "وکیل",
    relatedSlugs: ["consultant", "real-estate", "service-company"],
    crossToolLinks: [{ hub: "googlesabt", slug: "lawyer", anchor: "ثبت دفتر وکیل در گوگل مپ" }],
    industryPath: "lawyer",
  },
  {
    hub: "bizcard",
    slug: "real-estate",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال مشاور املاک",
    secondaryKeywords: ["کارت ویزیت املاک", "لینک مشاور املاک"],
    label: "املاک",
    relatedSlugs: ["lawyer", "service-company", "consultant"],
    crossToolLinks: [{ hub: "googlesabt", slug: "real-estate", anchor: "ثبت املاک در گوگل مپ" }],
    industryPath: "real-estate",
  },
  {
    hub: "bizcard",
    slug: "online-shop",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال فروشگاه",
    secondaryKeywords: ["لینک فروشگاه", "کارت ویزیت مغازه آنلاین"],
    label: "فروشگاه",
    relatedSlugs: ["instagram-business", "restaurant", "salon"],
    crossToolLinks: [
      { hub: "shortener", slug: "bio-link", anchor: "لینک کوتاه بیو فروشگاه" },
      { hub: "googlesabt", slug: "shop", anchor: "ثبت فروشگاه در گوگل مپ" },
    ],
    industryPath: "online-shop",
  },
  {
    hub: "bizcard",
    slug: "photographer",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال عکاس",
    secondaryKeywords: ["کارت ویزیت آتلیه", "لینک پورتفولیو عکاس"],
    label: "عکاس",
    relatedSlugs: ["freelancer", "architect", "instagram-business"],
    crossToolLinks: [{ hub: "googlesabt", slug: "photographer", anchor: "ثبت آتلیه در گوگل مپ" }],
    industryPath: "photographer",
  },
  {
    hub: "bizcard",
    slug: "architect",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال معمار",
    secondaryKeywords: ["کارت ویزیت دفتر معماری", "لینک نمونه کار معماری"],
    label: "معمار",
    relatedSlugs: ["photographer", "consultant", "freelancer"],
    industryPath: "architect",
  },
  {
    hub: "bizcard",
    slug: "consultant",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال مشاور",
    secondaryKeywords: ["لینک رزرو مشاوره", "کارت ویزیت مشاوره کسب‌وکار"],
    label: "مشاور",
    relatedSlugs: ["lawyer", "private-tutor", "freelancer"],
    industryPath: "consultant",
  },
  {
    hub: "bizcard",
    slug: "private-tutor",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال مدرس",
    secondaryKeywords: ["کارت ویزیت معلم خصوصی", "لینک ثبت‌نام کلاس"],
    label: "مدرس",
    relatedSlugs: ["consultant", "freelancer", "instagram-business"],
    industryPath: "private-tutor",
  },
  {
    hub: "bizcard",
    slug: "service-company",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال شرکت خدماتی",
    secondaryKeywords: ["لینک شرکت خدماتی", "کارت ویزیت خدمات"],
    label: "شرکت خدماتی",
    relatedSlugs: ["real-estate", "lawyer", "online-shop"],
    crossToolLinks: [
      { hub: "googlesabt", slug: "service-company", anchor: "ثبت شرکت خدماتی در گوگل مپ" },
    ],
    industryPath: "service-company",
  },
  {
    hub: "bizcard",
    slug: "instagram-business",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال اینستاگرام",
    secondaryKeywords: ["لینک بیو اینستاگرام", "لینک این‌بیو کسب‌وکار"],
    label: "اینستاگرام",
    relatedSlugs: ["online-shop", "salon", "freelancer", "cafe"],
    crossToolLinks: [
      { hub: "shortener", slug: "bio-link", anchor: "کوتاه‌کننده لینک بیو" },
      { hub: "qr", slug: "instagram", anchor: "QR اینستاگرام" },
      { hub: "googlesabt", slug: "shop", anchor: "ثبت کسب‌وکار در گوگل مپ" },
    ],
    industryPath: "instagram-business",
  },
  {
    hub: "bizcard",
    slug: "freelancer",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال فریلنسر",
    secondaryKeywords: ["کارت ویزیت فریلنسری", "لینک پورتفولیو فریلنسر"],
    label: "فریلنسر",
    relatedSlugs: ["photographer", "consultant", "architect", "instagram-business"],
  },
  {
    hub: "bizcard",
    slug: "salon",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال آرایشگاه",
    secondaryKeywords: ["کارت ویزیت سالن زیبایی", "لینک نوبت آرایشگاه"],
    label: "آرایشگاه",
    relatedSlugs: ["beauty-clinic", "cafe", "instagram-business", "gym"],
    crossToolLinks: [
      { hub: "qr", slug: "instagram", anchor: "QR پیج آرایشگاه" },
      { hub: "googlesabt", slug: "salon", anchor: "ثبت آرایشگاه در گوگل مپ" },
    ],
  },
  {
    hub: "bizcard",
    slug: "gym",
    pageType: "industry",
    status: "published",
    primaryKeyword: "کارت ویزیت دیجیتال باشگاه",
    secondaryKeywords: ["کارت ویزیت باشگاه ورزشی", "لینک ثبت‌نام باشگاه"],
    label: "باشگاه",
    relatedSlugs: ["salon", "cafe", "service-company"],
    crossToolLinks: [{ hub: "googlesabt", slug: "gym", anchor: "ثبت باشگاه در گوگل مپ" }],
  },
];

const QR_PAGES: ToolRegistryEntry[] = [
  // Social / messaging
  {
    hub: "qr",
    slug: "instagram",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد اینستاگرام",
    secondaryKeywords: ["QR پیج اینستاگرام", "کیو آر کد اینستا"],
    label: "اینستاگرام",
    relatedSlugs: ["whatsapp", "telegram", "business-card", "website"],
    crossToolLinks: [
      { hub: "bizcard", slug: "instagram-business", anchor: "کارت ویزیت برای اینستاگرام" },
      { hub: "shortener", slug: "instagram", anchor: "لینک کوتاه اینستاگرام" },
    ],
  },
  {
    hub: "qr",
    slug: "whatsapp",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد واتساپ",
    secondaryKeywords: ["QR واتس‌اپ", "کیو آر کد واتساپ کسب‌وکار"],
    label: "واتساپ",
    relatedSlugs: ["telegram", "phone", "sms", "instagram"],
    crossToolLinks: [{ hub: "shortener", slug: "whatsapp", anchor: "لینک کوتاه واتساپ" }],
  },
  {
    hub: "qr",
    slug: "telegram",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد تلگرام",
    secondaryKeywords: ["QR کانال تلگرام", "کیو آر کد تلگرام"],
    label: "تلگرام",
    relatedSlugs: ["whatsapp", "instagram", "eitaa", "rubika"],
  },
  {
    hub: "qr",
    slug: "linkedin",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد لینکدین",
    secondaryKeywords: ["QR پروفایل لینکدین"],
    label: "لینکدین",
    relatedSlugs: ["vcard", "website", "business-card"],
  },
  {
    hub: "qr",
    slug: "youtube",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد یوتیوب",
    secondaryKeywords: ["QR کانال یوتیوب"],
    label: "یوتیوب",
    relatedSlugs: ["aparat", "website", "instagram"],
  },
  {
    hub: "qr",
    slug: "aparat",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد آپارات",
    secondaryKeywords: ["QR کانال آپارات"],
    label: "آپارات",
    relatedSlugs: ["youtube", "instagram", "website"],
  },
  {
    hub: "qr",
    slug: "rubika",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد روبیکا",
    secondaryKeywords: ["QR روبیکا"],
    label: "روبیکا",
    relatedSlugs: ["eitaa", "telegram", "whatsapp"],
  },
  {
    hub: "qr",
    slug: "eitaa",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد ایتا",
    secondaryKeywords: ["QR ایتا"],
    label: "ایتا",
    relatedSlugs: ["rubika", "telegram", "whatsapp"],
  },
  // Content types
  {
    hub: "qr",
    slug: "wifi",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد وای‌فای",
    secondaryKeywords: ["QR وای فای", "کیو آر کد WiFi"],
    label: "وای‌فای",
    relatedSlugs: ["menu", "location", "business-card"],
    crossToolLinks: [{ hub: "bizcard", slug: "cafe", anchor: "کارت ویزیت کافه" }],
  },
  {
    hub: "qr",
    slug: "menu",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد منو",
    secondaryKeywords: ["QR منوی رستوران", "منوی دیجیتال QR"],
    label: "منو",
    relatedSlugs: ["wifi", "website", "google-maps", "instagram"],
    crossToolLinks: [{ hub: "bizcard", slug: "restaurant", anchor: "کارت ویزیت رستوران" }],
  },
  {
    hub: "qr",
    slug: "vcard",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد vCard",
    secondaryKeywords: ["QR کارت مخاطب", "کیو آر کد ذخیره مخاطب"],
    label: "vCard",
    relatedSlugs: ["business-card", "phone", "email", "linkedin"],
    crossToolLinks: [{ hub: "bizcard", slug: "doctor", anchor: "کارت ویزیت دیجیتال" }],
  },
  {
    hub: "qr",
    slug: "website",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد سایت",
    secondaryKeywords: ["QR وب‌سایت", "کیو آر کد لینک سایت"],
    label: "وب‌سایت",
    relatedSlugs: ["instagram", "google-maps", "product", "pdf"],
    crossToolLinks: [{ hub: "shortener", slug: "campaign", anchor: "لینک کوتاه کمپین" }],
  },
  {
    hub: "qr",
    slug: "pdf",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد PDF",
    secondaryKeywords: ["QR فایل PDF", "دانلود PDF با QR"],
    label: "PDF",
    relatedSlugs: ["website", "product", "menu"],
  },
  {
    hub: "qr",
    slug: "payment",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد پرداخت",
    secondaryKeywords: ["QR درگاه پرداخت", "کیو آر کد پرداخت"],
    label: "پرداخت",
    relatedSlugs: ["product", "website", "menu"],
  },
  {
    hub: "qr",
    slug: "location",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد لوکیشن",
    secondaryKeywords: ["QR موقعیت مکانی", "کیو آر کد آدرس"],
    label: "لوکیشن",
    relatedSlugs: ["google-maps", "wifi", "business-card"],
  },
  {
    hub: "qr",
    slug: "sms",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد پیامک",
    secondaryKeywords: ["QR SMS"],
    label: "پیامک",
    relatedSlugs: ["phone", "whatsapp", "email"],
  },
  {
    hub: "qr",
    slug: "phone",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد تماس تلفنی",
    secondaryKeywords: ["QR شماره تلفن", "کیو آر کد تماس"],
    label: "تماس",
    relatedSlugs: ["sms", "whatsapp", "vcard"],
  },
  {
    hub: "qr",
    slug: "email",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد ایمیل",
    secondaryKeywords: ["QR ایمیل"],
    label: "ایمیل",
    relatedSlugs: ["phone", "vcard", "linkedin"],
  },
  {
    hub: "qr",
    slug: "event",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد رویداد",
    secondaryKeywords: ["QR دعوتنامه", "کیو آر کد همایش"],
    label: "رویداد",
    relatedSlugs: ["website", "location", "whatsapp"],
  },
  {
    hub: "qr",
    slug: "product",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد محصول",
    secondaryKeywords: ["QR روی بسته‌بندی", "کیو آر کد کالا"],
    label: "محصول",
    relatedSlugs: ["website", "payment", "pdf"],
  },
  {
    hub: "qr",
    slug: "google-maps",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد گوگل مپ",
    secondaryKeywords: ["QR نقشه گوگل", "کیو آر کد گوگل مپس"],
    label: "گوگل مپ",
    relatedSlugs: ["location", "business-card", "wifi"],
  },
  {
    hub: "qr",
    slug: "business-card",
    pageType: "intent",
    status: "published",
    primaryKeyword: "ساخت QR کد کارت ویزیت",
    secondaryKeywords: ["QR روی کارت ویزیت", "کیو آر کد کارت"],
    label: "کارت ویزیت",
    relatedSlugs: ["vcard", "instagram", "website"],
    crossToolLinks: [{ hub: "bizcard", slug: "freelancer", anchor: "ساخت کارت ویزیت دیجیتال" }],
  },
  // Guides / comparisons
  {
    hub: "qr",
    slug: "how-to-print",
    pageType: "guide",
    status: "published",
    primaryKeyword: "چگونه QR کد را پرینت بگیریم",
    secondaryKeywords: ["راهنمای چاپ QR", "سایز مناسب QR برای چاپ"],
    label: "راهنمای چاپ",
    relatedSlugs: ["how-to-download", "menu", "business-card"],
  },
  {
    hub: "qr",
    slug: "how-to-download",
    pageType: "guide",
    status: "published",
    primaryKeyword: "چگونه QR کد را دانلود کنیم",
    secondaryKeywords: ["دانلود QR PNG", "ذخیره QR کد"],
    label: "راهنمای دانلود",
    relatedSlugs: ["how-to-print", "website", "instagram"],
  },
  {
    hub: "qr",
    slug: "qr-vs-barcode",
    pageType: "comparison",
    status: "published",
    primaryKeyword: "تفاوت QR کد و بارکد",
    secondaryKeywords: ["QR یا بارکد", "مقایسه QR و بارکد"],
    label: "QR در برابر بارکد",
    relatedSlugs: ["product", "menu", "best-qr-generator"],
  },
  {
    hub: "qr",
    slug: "best-qr-generator",
    pageType: "comparison",
    status: "published",
    primaryKeyword: "بهترین ابزار ساخت QR کد رایگان",
    secondaryKeywords: ["ژنراتور QR فارسی", "ساخت QR آنلاین"],
    label: "بهترین سازنده QR",
    relatedSlugs: ["how-to-download", "website", "instagram"],
  },
];

const SHORTENER_PAGES: ToolRegistryEntry[] = [
  {
    hub: "shortener",
    slug: "instagram",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک اینستاگرام",
    secondaryKeywords: ["لینک کوتاه بیو اینستا", "شورت لینک اینستاگرام"],
    label: "اینستاگرام",
    relatedSlugs: ["bio-link", "whatsapp", "campaign", "telegram"],
    crossToolLinks: [
      { hub: "qr", slug: "instagram", anchor: "QR اینستاگرام" },
      { hub: "bizcard", slug: "instagram-business", anchor: "کارت ویزیت اینستاگرامی" },
    ],
  },
  {
    hub: "shortener",
    slug: "whatsapp",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک واتساپ",
    secondaryKeywords: ["لینک کوتاه واتس‌اپ", "شورت لینک واتساپ"],
    label: "واتساپ",
    relatedSlugs: ["telegram", "sms", "instagram", "marketing"],
    crossToolLinks: [{ hub: "qr", slug: "whatsapp", anchor: "QR واتساپ" }],
  },
  {
    hub: "shortener",
    slug: "telegram",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک تلگرام",
    secondaryKeywords: ["لینک کوتاه کانال تلگرام"],
    label: "تلگرام",
    relatedSlugs: ["whatsapp", "instagram", "bio-link"],
  },
  {
    hub: "shortener",
    slug: "youtube",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک یوتیوب",
    secondaryKeywords: ["لینک کوتاه ویدیو یوتیوب"],
    label: "یوتیوب",
    relatedSlugs: ["podcast", "blog", "campaign"],
  },
  {
    hub: "shortener",
    slug: "linkedin",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک لینکدین",
    secondaryKeywords: ["لینک کوتاه لینکدین"],
    label: "لینکدین",
    relatedSlugs: ["email", "marketing", "blog"],
  },
  {
    hub: "shortener",
    slug: "sms",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک پیامک",
    secondaryKeywords: ["لینک کوتاه SMS", "شورت لینک پیامکی"],
    label: "پیامک",
    relatedSlugs: ["whatsapp", "campaign", "tracking"],
  },
  {
    hub: "shortener",
    slug: "email",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک ایمیل",
    secondaryKeywords: ["لینک کوتاه در خبرنامه"],
    label: "ایمیل",
    relatedSlugs: ["marketing", "campaign", "blog"],
  },
  {
    hub: "shortener",
    slug: "bio-link",
    pageType: "intent",
    status: "published",
    primaryKeyword: "لینک کوتاه برای بیو",
    secondaryKeywords: ["بیو لینک", "لینک این‌بیو"],
    label: "بیو لینک",
    relatedSlugs: ["instagram", "campaign", "qr-code"],
    crossToolLinks: [{ hub: "bizcard", slug: "instagram-business", anchor: "کارت ویزیت به‌جای لینک‌در‌بیو" }],
  },
  {
    hub: "shortener",
    slug: "campaign",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک کمپین تبلیغاتی",
    secondaryKeywords: ["لینک کوتاه کمپین", "شورت لینک تبلیغات"],
    label: "کمپین",
    relatedSlugs: ["marketing", "tracking", "affiliate", "sms"],
  },
  {
    hub: "shortener",
    slug: "affiliate",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک افیلیت",
    secondaryKeywords: ["لینک کوتاه همکاری در فروش"],
    label: "افیلیت",
    relatedSlugs: ["campaign", "tracking", "marketing"],
  },
  {
    hub: "shortener",
    slug: "event",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک رویداد",
    secondaryKeywords: ["لینک کوتاه ثبت‌نام همایش"],
    label: "رویداد",
    relatedSlugs: ["campaign", "whatsapp", "qr-code"],
    crossToolLinks: [{ hub: "qr", slug: "event", anchor: "QR رویداد" }],
  },
  {
    hub: "shortener",
    slug: "marketing",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک بازاریابی",
    secondaryKeywords: ["لینک کوتاه مارکتینگ"],
    label: "بازاریابی",
    relatedSlugs: ["campaign", "tracking", "email", "sms"],
  },
  {
    hub: "shortener",
    slug: "blog",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک مقاله",
    secondaryKeywords: ["لینک کوتاه بلاگ"],
    label: "بلاگ",
    relatedSlugs: ["youtube", "podcast", "email"],
  },
  {
    hub: "shortener",
    slug: "podcast",
    pageType: "intent",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک پادکست",
    secondaryKeywords: ["لینک کوتاه اپیزود"],
    label: "پادکست",
    relatedSlugs: ["youtube", "blog", "instagram"],
  },
  {
    hub: "shortener",
    slug: "qr-code",
    pageType: "intent",
    status: "published",
    primaryKeyword: "لینک کوتاه برای QR کد",
    secondaryKeywords: ["شورت لینک داخل QR"],
    label: "QR کد",
    relatedSlugs: ["campaign", "bio-link", "tracking"],
    crossToolLinks: [{ hub: "qr", slug: "website", anchor: "ساخت QR از لینک" }],
  },
  {
    hub: "shortener",
    slug: "tracking",
    pageType: "intent",
    status: "published",
    primaryKeyword: "لینک کوتاه با ردیابی",
    secondaryKeywords: ["شورت لینک UTM", "ردیابی کلیک لینک"],
    label: "ردیابی",
    relatedSlugs: ["campaign", "marketing", "affiliate"],
  },
  // Guides
  {
    hub: "shortener",
    slug: "how-it-works",
    pageType: "guide",
    status: "published",
    primaryKeyword: "کوتاه‌کننده لینک چطور کار می‌کند",
    secondaryKeywords: ["راهنمای لینک کوتاه"],
    label: "نحوه کار",
    relatedSlugs: ["custom-alias", "short-link-vs-full-url", "instagram"],
  },
  {
    hub: "shortener",
    slug: "custom-alias",
    pageType: "guide",
    status: "published",
    primaryKeyword: "آدرس دلخواه لینک کوتاه",
    secondaryKeywords: ["slug اختصاصی", "لینک کوتاه برند"],
    label: "آدرس دلخواه",
    relatedSlugs: ["how-it-works", "bio-link", "campaign"],
  },
  {
    hub: "shortener",
    slug: "short-link-vs-full-url",
    pageType: "comparison",
    status: "published",
    primaryKeyword: "لینک کوتاه در برابر لینک بلند",
    secondaryKeywords: ["مزایای لینک کوتاه"],
    label: "لینک کوتاه در برابر بلند",
    relatedSlugs: ["how-it-works", "marketing", "instagram"],
  },
];

const GOOGLESABT_PAGES: ToolRegistryEntry[] = [
  {
    hub: "googlesabt",
    slug: "restaurant",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت رستوران در گوگل مپ",
    secondaryKeywords: ["ثبت رستوران در گوگل", "ثبت فست‌فود در نقشه گوگل", "گوگل بیزینس رستوران"],
    label: "رستوران",
    relatedSlugs: ["cafe", "shop", "salon", "gym"],
    crossToolLinks: [
      { hub: "bizcard", slug: "restaurant", anchor: "کارت ویزیت دیجیتال رستوران" },
      { hub: "qr", slug: "menu", anchor: "QR منوی رستوران" },
    ],
    industryPath: "restaurant",
  },
  {
    hub: "googlesabt",
    slug: "cafe",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت کافه در گوگل مپ",
    secondaryKeywords: ["ثبت کافی‌شاپ در گوگل", "گوگل بیزینس کافه"],
    label: "کافه",
    relatedSlugs: ["restaurant", "salon", "shop", "gym"],
    crossToolLinks: [
      { hub: "bizcard", slug: "cafe", anchor: "کارت ویزیت دیجیتال کافه" },
      { hub: "qr", slug: "wifi", anchor: "QR وای‌فای کافه" },
    ],
    industryPath: "cafe",
  },
  {
    hub: "googlesabt",
    slug: "doctor",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت مطب پزشک در گوگل مپ",
    secondaryKeywords: ["ثبت پزشک در گوگل", "گوگل بیزینس مطب", "ثبت پزشک در نقشه"],
    label: "پزشک",
    relatedSlugs: ["clinic", "dentist", "beauty-clinic"],
    crossToolLinks: [
      { hub: "bizcard", slug: "doctor", anchor: "کارت ویزیت دیجیتال پزشک" },
    ],
    industryPath: "doctor",
  },
  {
    hub: "googlesabt",
    slug: "clinic",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت کلینیک در گوگل مپ",
    secondaryKeywords: ["ثبت مرکز درمانی در گوگل", "گوگل بیزینس کلینیک"],
    label: "کلینیک",
    relatedSlugs: ["doctor", "dentist", "beauty-clinic"],
    crossToolLinks: [{ hub: "bizcard", slug: "clinic", anchor: "کارت ویزیت دیجیتال کلینیک" }],
    industryPath: "clinic",
  },
  {
    hub: "googlesabt",
    slug: "dentist",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت دندانپزشکی در گوگل مپ",
    secondaryKeywords: ["ثبت مطب دندانپزشک در گوگل", "گوگل بیزینس دندانپزشکی"],
    label: "دندانپزشکی",
    relatedSlugs: ["doctor", "clinic", "beauty-clinic"],
    crossToolLinks: [{ hub: "bizcard", slug: "dentist", anchor: "کارت ویزیت دیجیتال دندانپزشک" }],
    industryPath: "dentist",
  },
  {
    hub: "googlesabt",
    slug: "beauty-clinic",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت کلینیک زیبایی در گوگل مپ",
    secondaryKeywords: ["ثبت پوست و مو در گوگل", "گوگل بیزینس کلینیک زیبایی"],
    label: "کلینیک زیبایی",
    relatedSlugs: ["salon", "clinic", "doctor"],
    crossToolLinks: [
      { hub: "bizcard", slug: "beauty-clinic", anchor: "کارت ویزیت دیجیتال کلینیک زیبایی" },
    ],
    industryPath: "beauty-clinic",
  },
  {
    hub: "googlesabt",
    slug: "lawyer",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت دفتر وکیل در گوگل مپ",
    secondaryKeywords: ["ثبت وکیل در گوگل", "گوگل بیزینس وکالت"],
    label: "وکیل",
    relatedSlugs: ["real-estate", "service-company", "shop"],
    crossToolLinks: [{ hub: "bizcard", slug: "lawyer", anchor: "کارت ویزیت دیجیتال وکیل" }],
    industryPath: "lawyer",
  },
  {
    hub: "googlesabt",
    slug: "real-estate",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت مشاور املاک در گوگل مپ",
    secondaryKeywords: ["ثبت املاک در گوگل", "گوگل بیزینس مشاور املاک"],
    label: "املاک",
    relatedSlugs: ["lawyer", "service-company", "shop"],
    crossToolLinks: [{ hub: "bizcard", slug: "real-estate", anchor: "کارت ویزیت دیجیتال املاک" }],
    industryPath: "real-estate",
  },
  {
    hub: "googlesabt",
    slug: "shop",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت فروشگاه در گوگل مپ",
    secondaryKeywords: ["ثبت مغازه در گوگل", "گوگل بیزینس فروشگاه"],
    label: "فروشگاه",
    relatedSlugs: ["restaurant", "salon", "service-company", "cafe"],
    crossToolLinks: [
      { hub: "bizcard", slug: "online-shop", anchor: "کارت ویزیت دیجیتال فروشگاه" },
    ],
    industryPath: "online-shop",
  },
  {
    hub: "googlesabt",
    slug: "salon",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت آرایشگاه در گوگل مپ",
    secondaryKeywords: ["ثبت سالن زیبایی در گوگل", "گوگل بیزینس آرایشگاه"],
    label: "آرایشگاه",
    relatedSlugs: ["beauty-clinic", "cafe", "gym", "shop"],
    crossToolLinks: [{ hub: "bizcard", slug: "salon", anchor: "کارت ویزیت دیجیتال آرایشگاه" }],
  },
  {
    hub: "googlesabt",
    slug: "gym",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت باشگاه در گوگل مپ",
    secondaryKeywords: ["ثبت باشگاه ورزشی در گوگل", "گوگل بیزینس باشگاه"],
    label: "باشگاه",
    relatedSlugs: ["salon", "cafe", "service-company"],
    crossToolLinks: [{ hub: "bizcard", slug: "gym", anchor: "کارت ویزیت دیجیتال باشگاه" }],
  },
  {
    hub: "googlesabt",
    slug: "photographer",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت آتلیه در گوگل مپ",
    secondaryKeywords: ["ثبت عکاس در گوگل", "گوگل بیزینس آتلیه"],
    label: "آتلیه",
    relatedSlugs: ["salon", "shop", "service-company"],
    crossToolLinks: [
      { hub: "bizcard", slug: "photographer", anchor: "کارت ویزیت دیجیتال عکاس" },
    ],
    industryPath: "photographer",
  },
  {
    hub: "googlesabt",
    slug: "service-company",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت شرکت خدماتی در گوگل مپ",
    secondaryKeywords: ["ثبت خدمات در گوگل", "گوگل بیزینس شرکت خدماتی"],
    label: "شرکت خدماتی",
    relatedSlugs: ["real-estate", "lawyer", "shop"],
    crossToolLinks: [
      { hub: "bizcard", slug: "service-company", anchor: "کارت ویزیت دیجیتال شرکت خدماتی" },
    ],
    industryPath: "service-company",
  },
  {
    hub: "googlesabt",
    slug: "pharmacy",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت داروخانه در گوگل مپ",
    secondaryKeywords: ["ثبت داروخانه در گوگل", "گوگل بیزینس داروخانه"],
    label: "داروخانه",
    relatedSlugs: ["clinic", "doctor", "shop"],
    crossToolLinks: [{ hub: "qr", slug: "google-maps", anchor: "QR گوگل مپ" }],
  },
  {
    hub: "googlesabt",
    slug: "hotel",
    pageType: "industry",
    status: "published",
    primaryKeyword: "ثبت هتل و اقامتگاه در گوگل مپ",
    secondaryKeywords: ["ثبت هتل در گوگل", "ثبت مهمان‌پذیر در نقشه"],
    label: "هتل",
    relatedSlugs: ["restaurant", "cafe", "shop"],
    crossToolLinks: [{ hub: "qr", slug: "location", anchor: "QR لوکیشن" }],
  },
];

export const TOOL_PROGRAMMATIC_PAGES: readonly ToolRegistryEntry[] = [
  ...BIZCARD_PAGES,
  ...QR_PAGES,
  ...SHORTENER_PAGES,
  ...GOOGLESABT_PAGES,
];

export function getToolPage(hub: ToolHub, slug: string): ToolRegistryEntry | undefined {
  return TOOL_PROGRAMMATIC_PAGES.find((p) => p.hub === hub && p.slug === slug);
}

export function isPublishedToolPage(hub: ToolHub, slug: string): boolean {
  return getToolPage(hub, slug)?.status === "published";
}

export function getPublishedToolPages(hub: ToolHub): ToolRegistryEntry[] {
  return TOOL_PROGRAMMATIC_PAGES.filter((p) => p.hub === hub && p.status === "published");
}

export function getPublishedToolPaths(): string[] {
  return TOOL_PROGRAMMATIC_PAGES.filter((p) => p.status === "published").map(
    (p) => `/${p.hub}/${p.slug}`,
  );
}

export function getHubLabel(hub: ToolHub): string {
  if (hub === "bizcard") return "کارت ویزیت دیجیتال";
  if (hub === "qr") return "ساخت QR کد";
  if (hub === "shortener") return "کوتاه‌کننده لینک";
  return "ثبت گوگل مپ";
}

export function getHubPath(hub: ToolHub): string {
  return `/${hub}`;
}
